import { z } from 'zod';

const isTimeZone = (tz: string) => {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: tz });
    return true;
  } catch {
    return false;
  }
};

// Format produced by utils/password.ts: scrypt:<N>:<salt>:<hash>, base64url.
// Colons (not `$`) so Docker Compose and dotenv don't treat parts as variables.
const PASSWORD_HASH = /^scrypt:\d+:[\w-]+:[\w-]+$/;

const envSchema = z.object({
  DATABASE_URL: z.string().regex(/^postgres(ql)?:\/\//, 'must be a postgres:// connection URL'),
  APP_PASSWORD_HASH: z
    .string()
    .regex(PASSWORD_HASH, 'must be generated by `npm run hash-password`'),
  SESSION_SECRET: z.string().min(32, 'must be at least 32 characters'),
  COOKIE_SECURE: z
    .enum(['true', 'false'], 'must be "true" or "false"')
    .default('false')
    .transform((v) => v === 'true'),
  PORT: z.coerce.number().int().min(1).max(65535).default(3000),
  TZ: z.string().refine(isTimeZone, 'must be an IANA time zone').default('America/New_York'),
});

export type Env = z.infer<typeof envSchema>;

export class EnvError extends Error {
  override readonly name = 'EnvError';
}

/** Validates the environment. Error messages name variables but never echo their values. */
export function parseEnv(source: Record<string, string | undefined>): Env {
  const result = envSchema.safeParse(source);
  if (result.success) return result.data;

  const problems = result.error.issues.map((issue) => {
    const key = issue.path.join('.');
    const reason = issue.code === 'invalid_type' ? 'is required' : issue.message;
    return `  - ${key} ${reason}`;
  });
  throw new EnvError(`Invalid environment configuration:\n${problems.join('\n')}`);
}

let cached: Env | undefined;

/** Validated server environment, parsed once from process.env. */
export function env(): Env {
  cached ??= parseEnv(process.env);
  return cached;
}
