import { z } from 'zod';

const isTimeZone = (tz: string) => {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: tz });
    return true;
  } catch {
    return false;
  }
};

// Format produced by utils/password.ts: scrypt:<N>:<salt>:<hash>, base64url.
// Colons (not `$`) so Docker Compose and dotenv don't treat parts as variables.
const PASSWORD_HASH = /^scrypt:\d+:[\w-]+:[\w-]+$/;

const envSchema = z.object({
  DATABASE_URL: z.string().regex(/^postgres(ql)?:\/\//, 'must be a postgres:// connection URL'),
  APP_PASSWORD_HASH: z
    .string()
    .regex(PASSWORD_HASH, 'must be generated by `npm run hash-password`'),
  SESSION_SECRET: z.string().min(32, 'must be at least 32 characters'),
  COOKIE_SECURE: z
    .enum(['true', 'false'], 'must be "true" or "false"')
    .default('false')
    .transform((v) => v === 'true'),
  PORT: z.coerce.number().int().min(1).max(65535).default(3000),
  TZ: z.string().refine(isTimeZone, 'must be an IANA time zone').default('America/New_York'),
  RXNAV_BASE_URL: z
    .url({ protocol: /^https?$/, error: 'must be an http(s) URL' })
    .default('https://rxnav.nlm.nih.gov/REST'),
  OPENFDA_BASE_URL: z
    .url({ protocol: /^https?$/, error: 'must be an http(s) URL' })
    .default('https://api.fda.gov/drug'),
  MEDLINEPLUS_BASE_URL: z
    .url({ protocol: /^https?$/, error: 'must be an http(s) URL' })
    .default('https://connect.medlineplus.gov/service'),
  // AI summaries: a local Ollama model by default, Claude optional.
  SUMMARY_PROVIDER: z.enum(['ollama', 'claude'], 'must be "ollama" or "claude"').default('ollama'),
  OLLAMA_BASE_URL: z
    .url({ protocol: /^https?$/, error: 'must be an http(s) URL' })
    // 127.0.0.1, not localhost: Node may resolve localhost to ::1 while Ollama listens on IPv4.
    .default('http://127.0.0.1:11434'),
  OLLAMA_MODEL: z.string().trim().min(1).optional(),
  OLLAMA_NUM_CTX: z.coerce.number().int().min(2048).max(262144).default(16384),
  OLLAMA_TIMEOUT_MS: z.coerce.number().int().min(10_000).default(600_000),
  ANTHROPIC_API_KEY: z.string().trim().min(1).optional(),
  AI_DAILY_LIMIT: z.coerce.number().int().min(0).default(20),
  // Optional; raises openFDA's daily limit. Sent as a query parameter, never logged.
  OPENFDA_API_KEY: z.string().trim().min(1).optional(),
});

export type Env = z.infer<typeof envSchema>;

export class EnvError extends Error {
  override readonly name = 'EnvError';
}

/** Validates the environment. Error messages name variables but never echo their values. */
export function parseEnv(source: Record<string, string | undefined>): Env {
  const result = envSchema.safeParse(source);
  if (result.success) return result.data;

  const problems = result.error.issues.map((issue) => {
    const key = issue.path.join('.');
    const reason = issue.code === 'invalid_type' ? 'is required' : issue.message;
    return `  - ${key} ${reason}`;
  });
  throw new EnvError(`Invalid environment configuration:\n${problems.join('\n')}`);
}

let cached: Env | undefined;

/** Validated server environment, parsed once from process.env. */
export function env(): Env {
  cached ??= parseEnv(process.env);
  return cached;
}
